import localFont from "next/font/local";
import "./globals.css";
// 1. IMPORT ALL PROVIDERS
import { 
  DestinationContextProvider, 
  SourceContextProvider, 
  CarSelectionContextProvider,
  AuthContextProvider // <-- Including the new Auth provider
} from "./utils/Context";

const uberRegular = localFont({
  src: "../public/fonts/UberMoveText-Regular.woff2",
  variable: "--font-uber-regular",
});

const uberMedium = localFont({
  src: "../public/fonts/UberMoveText-Medium.woff2",
  variable: "--font-uber-medium",
});

export const metadata = {
  title: "UberClone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // 2. The <html> tag MUST be the top-level element
    <html lang="en">
      <body className={`${uberRegular.variable} ${uberMedium.variable}`}>
        {/* 3. Move all providers INSIDE the <body> tag */}
        <AuthContextProvider>
          <SourceContextProvider>
            <DestinationContextProvider>
              <CarSelectionContextProvider>
                {children}
              </CarSelectionContextProvider>
            </DestinationContextProvider>
          </SourceContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}

